import Head from 'next/head';
import { Box, Text } from '@chakra-ui/react';

import NavBar from '../components/NavBar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Artisans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        height="100vh"
        width="100vw"
        background="url('../../images/landing-bg.svg') no-repeat"
        backgroundSize="cover"
      >
        <NavBar />
      </Box>
    </>
  );
}
